### ISSUE TITLE
Add warnings for missing endpoints

### ISSUE THREAD

**Issue by stephenlacy** [ajoslin/observ-falcor#1]
A few warnings and error messages such as the following would be helpful:
- Emit an error when a route is lacking the `length` property and fails to retrieve the data on `fetchRangeAndData`. https://github.com/ajoslin/observ-falcor/blob/master/list/index.js#L51
- Emit a warning when the endpoint returns a non falcor data shape.

Adding the full path used to request to the server would also be helpful for debugging.
Also adding documentation for indicating the needed routes and responses would be helpful.

I should be able to get around to most of these in the upcoming weeks.

**Comment by ajoslin** [comment]
https://github.com/ajoslin/observ-falcor/blob/master/list/index.js#L55

What did you end up seeing in the error log? This, or something else?

**Comment by ajoslin** [comment]
One other thing that can be done: if no callback is provided, throw errors by default.

**Comment by stephenlacy** [comment]
Yes, that was the error in the callback - I ended up looking for where it was getting thrown to figure out why it was stating there was no data on the prefix. At that point I realized that there also needs to be a `length` route

**Comment by ajoslin** [comment]
OK. So we can do two things:
- Make sure the error explicitly states a `length` property is needed, and `from` will default 0 if not provided
- Throw errors if no callback is provided.

**Comment by ajoslin** [comment]
`1.1.1` released with better errors. Thanks Steve.
